### ISSUE TITLE
error:  Choice >>: 2023/03/10 14:59:32 Timed out waiting for pipe '\\.\pipe\discord-ipc-0' to come available

### ISSUE THREAD

**Issue by vst212** [YABOIpy/Go-MassDM#4]
Choice >>: 2023/03/10 14:59:32 Timed out waiting for pipe '\\.\pipe\discord-ipc-0' to come available

I am sorry to ask any ideas how to settle this?

Thanks.

**Comment by YABOIpy** [comment]
Go to config.json and disable presence and u should be good to go

**Comment by vst212** [comment]
thanks! it works!
