### ISSUE TITLE
Closed by remote host

### ISSUE THREAD

**Issue by Mouad-scriptz** [YABOIpy/Go-MassDM#7]
![image](https://user-images.githubusercontent.com/102869034/224431413-082dc4f5-94d4-4f68-ac12-5c3fd65d65c3.png)
reason may be too much tokens because im using high end pool iproyal proxies please make it pass errors and continue (im still new to go)

**Comment by YABOIpy** [comment]
what function were u using?

**Comment by Mouad-scriptz** [comment]
joiner

**Comment by YABOIpy** [comment]
are u usting residentail rotating proxies or did u just use a random free one?

**Comment by Mouad-scriptz** [comment]
bruh i already told you iproyal

**Comment by YABOIpy** [comment]
My bad.
U sure u dont have them on static? Or have any balance on them

**Comment by Mouad-scriptz** [comment]
1.5G and rotating

**Comment by Mouad-scriptz** [comment]
what provider are you using?

**Comment by YABOIpy** [comment]
me and other people also use iproyal and it works fine with this
