### ISSUE TITLE
how does the captcha bypass work?

### ISSUE THREAD

**Issue by goldego** [YABOIpy/Go-MassDM#9]
I'm new to all this stuff, I'm using capmonster but when I put my api key in, it doesn't actually solve the captcha.

do i need to specify the service in the config? it isn't very clear how you do this

**Comment by YABOIpy** [comment]
yeah im trying to resolve the issue it might be that capmonster isnt solving the captchas right or something is being sent wrong / flagged

**Comment by goldego** [comment]
alright thanks
